# Generated by Django 4.2.2 on 2023-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
